const portfolioData = [
    {
        index: 0,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-1.webp",
        category: "Web Development",
        year: "2023",
        tag: "Featured",
        title: "Enterprise Analytics Dashboard",
        description:"Nulla porttitor accumsan tincidunt. Vivamus suscipit tortor eget felis porttitor volutpat.",
        tags: ["Analytics", "Dashboard", "SaaS"],
        linkText: "View Case Study",
    },
    {
        index: 1,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-3.webp",
        category: "Mobile Apps",
        year: "2023",
        title: "Fitness Tracking Application",
        description: "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.",
        tags: ["Fitness", "iOS", "Android"],
        linkText: "View Case Study",
    },
    {
        index: 2,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-5.webp",
        category: "Branding",
        year: "2023",
        tag: "Award Winner",
        title: "Tech Startup Brand Identity",
        description: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
        tags: ["Branding", "Print", "All-New Design"],
        linkText: "View Case Study",
    },
    {
        index: 3,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-7.webp",
        category: "UI/UX Design",
        year: "2022",
        title: "Cloud-Based SaaS Platform",
        description: "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.",
        tags: ["Dashboard", "Design System"],
        linkText: "View Case Study",
    },
    {
        index: 4,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-2.webp",
        category: "Web Development",
        year: "2022",
        title: "Multi-Vendor E-commerce",
        description: "Donec sollicitudin molestie malesuada. Curabitur arcu erat, accumsan et imperdiet.",
        tags: ["E-commerce", "Stripe", "Shopify"],
        linkText: "View Case Study",
    },
    {
        index: 5,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-4.webp",
        category: "Mobile Apps",
        year: "2022",
        tag: "Featured",
        title: "Digital Banking Solution",
        description: "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
        tags: ["Banking", "Finance", "Secure API"],
        linkText: "View Case Study",
    },
    {
        index: 6,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-6.webp",
        category: "Web Development",
        year: "2021",
        title: "Property Listing Platform",
        description: "Donec rutrum congue leo eget malesuada. Nulla quis lorem ut libero malesuada.",
        tags: ["Real Estate", "Portal"],
        linkText: "View Case Study",
    },
    {
        index: 7,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-9.webp",
        category: "Branding",
        year: "2021",
        title: "Restaurant Chain Rebrand",
        description: "Pellentesque in ipsum id orci porta dapibus. Sed porttitor lectus nibh.",
        tags: ["Branding", "Print Design", "Packaging"],
        linkText: "View Case Study",
    },
    {
        index: 8,
        img: "https://bootstrapmade.com/content/demo/Forma/assets/img/portfolio/portfolio-8.webp",
        category: "UI/UX Design",
        year: "2021",
        title: "Patient Management Portal",
        description: "Quisque velit nisi, pretium ut lacinia in, elementum id enim.",
        tags: ["Healthcare", "Medical", "System"],
        linkText: "View Case Study",
    },
];

export default portfolioData;